<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi\Api;

use MultiFlexi\Api\DefaultApi;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:35.
 *
 * @no-named-arguments
 */
class DefaultApiTest extends \PHPUnit\Framework\TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new DefaultApi();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Api\DefaultApi::rootGet
     *
     * @todo   Implement testrootGet().
     */
    public function testrootGet(): void
    {
        $this->assertEquals('', $this->object->rootGet());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Api\DefaultApi::loginGet
     *
     * @todo   Implement testloginGet().
     */
    public function testloginGet(): void
    {
        $this->assertEquals('', $this->object->loginGet());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Api\DefaultApi::getApiIndex
     *
     * @todo   Implement testgetApiIndex().
     */
    public function testgetApiIndex(): void
    {
        $this->assertEquals('', $this->object->getApiIndex());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Api\DefaultApi::pingsuffixGet
     *
     * @todo   Implement testpingsuffixGet().
     */
    public function testpingsuffixGet(): void
    {
        $this->assertEquals('', $this->object->pingsuffixGet());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Api\DefaultApi::prepareResponse
     *
     * @todo   Implement testprepareResponse().
     */
    public function testprepareResponse(): void
    {
        $this->assertEquals('', $this->object->prepareResponse());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Api\DefaultApi::arrayToXml
     *
     * @todo   Implement testarrayToXml().
     */
    public function testarrayToXml(): void
    {
        $this->assertEquals('', $this->object->arrayToXml());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
