<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi\Api;

use MultiFlexi\Api\ServerApi;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:36.
 */
class ServerApiTest extends \PHPUnit\Framework\TestCase
{
    protected ServerApi $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ServerApi();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Api\ServerApi::getServerById
     *
     * @todo   Implement testgetServerById().
     */
    public function testgetServerById(): void
    {
        $this->assertEquals('', $this->object->getServerById());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Api\ServerApi::listServers
     *
     * @todo   Implement testlistServers().
     */
    public function testlistServers(): void
    {
        $this->assertEquals('', $this->object->listServers());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Api\ServerApi::setServerById
     *
     * @todo   Implement testsetServerById().
     */
    public function testsetServerById(): void
    {
        $this->assertEquals('', $this->object->setServerById());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
