FROM docker.io/library/bash
COPY bin/multiflexi-probe /usr/bin
RUN chmod +x /usr/bin/multiflexi-probe
CMD ["/usr/bin/multiflexi-probe"]

LABEL maintainer="Vítězslav Dvořák <info@vitexsoftware.cz>"
LABEL description="Container for running the MultiFlexi probe."
LABEL version="1.1.1"
