FROM debian:stable-slim
RUN apt-get update && \
	apt-get dist-upgrade -y && \
	apt-get install -y --no-install-recommends bash && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*
COPY bin/multiflexi-probe /usr/bin
RUN chmod +x /usr/bin/multiflexi-probe
CMD ["/usr/bin/multiflexi-probe"]

LABEL maintainer="Vítězslav Dvořák <info@vitexsoftware.cz>"
LABEL description="Container for running the MultiFlexi probe."
LABEL version="1.1.2"
