<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi\Ui;

use MultiFlexi\Ui\ActionsChooser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-11-07 at 12:16:41.
 *
 * @no-named-arguments
 */
class ActionsChooserTest extends \PHPUnit\Framework\TestCase
{
    protected ActionsChooser $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ActionsChooser();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Ui\ActionsChooser::toggles
     *
     * @todo   Implement testtoggles().
     */
    public function testtoggles(): void
    {
        $this->assertEquals('', $this->object->toggles());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ActionsChooser::formModuleCofig
     *
     * @todo   Implement testformModuleCofig().
     */
    public function testformModuleCofig(): void
    {
        $this->assertEquals('', $this->object->formModuleCofig());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ActionsChooser::sqlToForm
     *
     * @todo   Implement testsqlToForm().
     */
    public function testsqlToForm(): void
    {
        $this->assertEquals('', $this->object->sqlToForm());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
