<?php

namespace Test\MultiFlexi\Ui;

use MultiFlexi\Ui\ApplicationInfo;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:31.
 */
class ApplicationInfoTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var ApplicationInfo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ApplicationInfo();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers MultiFlexi\Ui\ApplicationInfo::headerRow
     * @todo   Implement testheaderRow().
     */
    public function testheaderRow()
    {
        $this->assertEquals('', $this->object->headerRow());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
