<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi\Ui;

use MultiFlexi\Ui\AppsSelector;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-11-07 at 12:16:38.
 *
 * @no-named-arguments
 */
class AppsSelectorTest extends \PHPUnit\Framework\TestCase
{
    protected AppsSelector $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new AppsSelector();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Ui\AppsSelector::availbleApps
     *
     * @todo   Implement testavailbleApps().
     */
    public function testavailbleApps(): void
    {
        $this->assertEquals('', $this->object->availbleApps());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\AppsSelector::translateColumns
     *
     * @todo   Implement testtranslateColumns().
     */
    public function testtranslateColumns(): void
    {
        $this->assertEquals('', $this->object->translateColumns());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\AppsSelector::selectize
     *
     * @todo   Implement testselectize().
     */
    public function testselectize(): void
    {
        $this->assertEquals('', $this->object->selectize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
