<?php

namespace Test\MultiFlexi\Ui;

use MultiFlexi\Ui\ColumnsForm;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:18.
 */
class ColumnsFormTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var ColumnsForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ColumnsForm();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers MultiFlexi\Ui\ColumnsForm::newRow
     * @todo   Implement testnewRow().
     */
    public function testnewRow()
    {
        $this->assertEquals('', $this->object->newRow());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Ui\ColumnsForm::addInput
     * @todo   Implement testaddInput().
     */
    public function testaddInput()
    {
        $this->assertEquals('', $this->object->addInput());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Ui\ColumnsForm::addSubmitSave
     * @todo   Implement testaddSubmitSave().
     */
    public function testaddSubmitSave()
    {
        $this->assertEquals('', $this->object->addSubmitSave());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Ui\ColumnsForm::addSubmitSaveAndList
     * @todo   Implement testaddSubmitSaveAndList().
     */
    public function testaddSubmitSaveAndList()
    {
        $this->assertEquals('', $this->object->addSubmitSaveAndList());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Ui\ColumnsForm::addSubmitSaveAndNext
     * @todo   Implement testaddSubmitSaveAndNext().
     */
    public function testaddSubmitSaveAndNext()
    {
        $this->assertEquals('', $this->object->addSubmitSaveAndNext());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Ui\ColumnsForm::finalize
     * @todo   Implement testfinalize().
     */
    public function testfinalize()
    {
        $this->assertEquals('', $this->object->finalize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
