<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi\Ui;

use MultiFlexi\Ui\ColumnsForm;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:18.
 */
class ColumnsFormTest extends \PHPUnit\Framework\TestCase
{
    protected ColumnsForm $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ColumnsForm();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Ui\ColumnsForm::newRow
     *
     * @todo   Implement testnewRow().
     */
    public function testnewRow(): void
    {
        $this->assertEquals('', $this->object->newRow());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ColumnsForm::addInput
     *
     * @todo   Implement testaddInput().
     */
    public function testaddInput(): void
    {
        $this->assertEquals('', $this->object->addInput());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ColumnsForm::addSubmitSave
     *
     * @todo   Implement testaddSubmitSave().
     */
    public function testaddSubmitSave(): void
    {
        $this->assertEquals('', $this->object->addSubmitSave());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ColumnsForm::addSubmitSaveAndList
     *
     * @todo   Implement testaddSubmitSaveAndList().
     */
    public function testaddSubmitSaveAndList(): void
    {
        $this->assertEquals('', $this->object->addSubmitSaveAndList());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ColumnsForm::addSubmitSaveAndNext
     *
     * @todo   Implement testaddSubmitSaveAndNext().
     */
    public function testaddSubmitSaveAndNext(): void
    {
        $this->assertEquals('', $this->object->addSubmitSaveAndNext());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ColumnsForm::finalize
     *
     * @todo   Implement testfinalize().
     */
    public function testfinalize(): void
    {
        $this->assertEquals('', $this->object->finalize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
