<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi\Ui;

use MultiFlexi\Ui\ConfigurationWizard;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2026-11-07 at 12:16:35.
 *
 * @no-named-arguments
 */
class ConfigurationWizardTest extends \PHPUnit\Framework\TestCase
{
    protected ConfigurationWizard $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ConfigurationWizard();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Ui\ConfigurationWizard::steps
     *
     * @todo   Implement teststeps().
     */
    public function teststeps(): void
    {
        $this->assertEquals('', $this->object->steps());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ConfigurationWizard::getStepBody
     *
     * @todo   Implement testgetStepBody().
     */
    public function testgetStepBody(): void
    {
        $this->assertEquals('', $this->object->getStepBody());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ConfigurationWizard::appConfigurator
     *
     * @todo   Implement testappConfigurator().
     */
    public function testappConfigurator(): void
    {
        $this->assertEquals('', $this->object->appConfigurator());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ConfigurationWizard::appChooser
     *
     * @todo   Implement testappChooser().
     */
    public function testappChooser(): void
    {
        $this->assertEquals('', $this->object->appChooser());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
