<?php

namespace Test\MultiFlexi\Ui;

use MultiFlexi\Ui\LogViewer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:31.
 */
class LogViewerTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var LogViewer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new LogViewer();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}
