<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi\Ui;

use MultiFlexi\Ui\RuntemplateJobsListing;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-11-07 at 12:16:55.
 */
class RuntemplateJobsListingTest extends \PHPUnit\Framework\TestCase
{
    protected RuntemplateJobsListing $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new RuntemplateJobsListing();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Ui\RuntemplateJobsListing::getJobs
     *
     * @todo   Implement testgetJobs().
     */
    public function testgetJobs(): void
    {
        $this->assertEquals('', $this->object->getJobs());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
