<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi\Ui;

use MultiFlexi\Ui\ServerSelect;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:25.
 */
class ServerSelectTest extends \PHPUnit\Framework\TestCase
{
    protected ServerSelect $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ServerSelect();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::loadItems
     *
     * @todo   Implement testloadItems().
     */
    public function testloadItems(): void
    {
        $this->assertEquals('', $this->object->loadItems());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::setUpDb
     *
     * @todo   Implement testsetUpDb().
     */
    public function testsetUpDb(): void
    {
        $this->assertEquals('', $this->object->setUpDb());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::setUp
     *
     * @todo   Implement testsetUp().
     */
    public function testsetUp(): void
    {
        $this->assertEquals('', $this->object->setUp());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::pdoConnect
     *
     * @todo   Implement testpdoConnect().
     */
    public function testpdoConnect(): void
    {
        $this->assertEquals('', $this->object->pdoConnect());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::getPdo
     *
     * @todo   Implement testgetPdo().
     */
    public function testgetPdo(): void
    {
        $this->assertEquals('', $this->object->getPdo());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::getFluentPDO
     *
     * @todo   Implement testgetFluentPDO().
     */
    public function testgetFluentPDO(): void
    {
        $this->assertEquals('', $this->object->getFluentPDO());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::listingQuery
     *
     * @todo   Implement testlistingQuery().
     */
    public function testlistingQuery(): void
    {
        $this->assertEquals('', $this->object->listingQuery());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::getColumnsFromSQL
     *
     * @todo   Implement testgetColumnsFromSQL().
     */
    public function testgetColumnsFromSQL(): void
    {
        $this->assertEquals('', $this->object->getColumnsFromSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::getDataFromSQL
     *
     * @todo   Implement testgetDataFromSQL().
     */
    public function testgetDataFromSQL(): void
    {
        $this->assertEquals('', $this->object->getDataFromSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::loadFromSQL
     *
     * @todo   Implement testloadFromSQL().
     */
    public function testloadFromSQL(): void
    {
        $this->assertEquals('', $this->object->loadFromSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::dbreload
     *
     * @todo   Implement testdbreload().
     */
    public function testdbreload(): void
    {
        $this->assertEquals('', $this->object->dbreload());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::dbsync
     *
     * @todo   Implement testdbsync().
     */
    public function testdbsync(): void
    {
        $this->assertEquals('', $this->object->dbsync());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::updateToSQL
     *
     * @todo   Implement testupdateToSQL().
     */
    public function testupdateToSQL(): void
    {
        $this->assertEquals('', $this->object->updateToSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::saveToSQL
     *
     * @todo   Implement testsaveToSQL().
     */
    public function testsaveToSQL(): void
    {
        $this->assertEquals('', $this->object->saveToSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::insertToSQL
     *
     * @todo   Implement testinsertToSQL().
     */
    public function testinsertToSQL(): void
    {
        $this->assertEquals('', $this->object->insertToSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::deleteFromSQL
     *
     * @todo   Implement testdeleteFromSQL().
     */
    public function testdeleteFromSQL(): void
    {
        $this->assertEquals('', $this->object->deleteFromSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::takeToData
     *
     * @todo   Implement testtakeToData().
     */
    public function testtakeToData(): void
    {
        $this->assertEquals('', $this->object->takeToData());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::getMyTable
     *
     * @todo   Implement testgetMyTable().
     */
    public function testgetMyTable(): void
    {
        $this->assertEquals('', $this->object->getMyTable());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::setMyTable
     *
     * @todo   Implement testsetMyTable().
     */
    public function testsetMyTable(): void
    {
        $this->assertEquals('', $this->object->setMyTable());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::getMyKey
     *
     * @todo   Implement testgetMyKey().
     */
    public function testgetMyKey(): void
    {
        $this->assertEquals('', $this->object->getMyKey());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::setMyKey
     *
     * @todo   Implement testsetMyKey().
     */
    public function testsetMyKey(): void
    {
        $this->assertEquals('', $this->object->setMyKey());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::getKeyColumn
     *
     * @todo   Implement testgetKeyColumn().
     */
    public function testgetKeyColumn(): void
    {
        $this->assertEquals('', $this->object->getKeyColumn());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\ServerSelect::setKeyColumn
     *
     * @todo   Implement testsetKeyColumn().
     */
    public function testsetKeyColumn(): void
    {
        $this->assertEquals('', $this->object->setKeyColumn());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
