<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi\Ui;

use MultiFlexi\Ui\Wizard;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2026-11-07 at 12:17:05.
 *
 * @no-named-arguments
 */
class WizardTest extends \PHPUnit\Framework\TestCase
{
    protected Wizard $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Wizard();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Ui\Wizard::getPreviousStep
     *
     * @todo   Implement testgetPreviousStep().
     */
    public function testgetPreviousStep(): void
    {
        $this->assertEquals('', $this->object->getPreviousStep());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\Wizard::getNextStep
     *
     * @todo   Implement testgetNextStep().
     */
    public function testgetNextStep(): void
    {
        $this->assertEquals('', $this->object->getNextStep());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\Wizard::getStepLabel
     *
     * @todo   Implement testgetStepLabel().
     */
    public function testgetStepLabel(): void
    {
        $this->assertEquals('', $this->object->getStepLabel());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\Wizard::getStepPercent
     *
     * @todo   Implement testgetStepPercent().
     */
    public function testgetStepPercent(): void
    {
        $this->assertEquals('', $this->object->getStepPercent());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Ui\Wizard::getStepBody
     *
     * @todo   Implement testgetStepBody().
     */
    public function testgetStepBody(): void
    {
        $this->assertEquals('', $this->object->getStepBody());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
