<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi\Zabbix\Request;

use MultiFlexi\Zabbix\Request\Metric;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:05.
 */
class MetricTest extends \PHPUnit\Framework\TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Metric();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Zabbix\Request\Metric::withHostname
     *
     * @todo   Implement testwithHostname().
     */
    public function testwithHostname(): void
    {
        $this->assertEquals('', $this->object->withHostname());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Zabbix\Request\Metric::withTimestamp
     *
     * @todo   Implement testwithTimestamp().
     */
    public function testwithTimestamp(): void
    {
        $this->assertEquals('', $this->object->withTimestamp());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Zabbix\Request\Metric::jsonSerialize
     *
     * @todo   Implement testjsonSerialize().
     */
    public function testjsonSerialize(): void
    {
        $this->assertEquals('', $this->object->jsonSerialize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
