<?php

namespace Test\MultiFlexi\Zabbix\Request;

use MultiFlexi\Zabbix\Request\Packet;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:06.
 */
class PacketTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Packet
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Packet();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers MultiFlexi\Zabbix\Request\Packet::addMetric
     * @todo   Implement testaddMetric().
     */
    public function testaddMetric()
    {
        $this->assertEquals('', $this->object->addMetric());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Zabbix\Request\Packet::getPacket
     * @todo   Implement testgetPacket().
     */
    public function testgetPacket()
    {
        $this->assertEquals('', $this->object->getPacket());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Zabbix\Request\Packet::jsonSerialize
     * @todo   Implement testjsonSerialize().
     */
    public function testjsonSerialize()
    {
        $this->assertEquals('', $this->object->jsonSerialize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
