// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login', async function() {
    await driver.get("http://172.22.208.22/MultiFlexi/src/logout.php")
    await driver.manage().window().maximize()
    
    // Handle GDPR consent banner
    try {
      const gdprAcceptButton = await driver.wait(until.elementLocated(By.id("consent-accept-all")), 3000)
      await gdprAcceptButton.click()
      await driver.sleep(500)
    } catch (e) {
      // GDPR banner might not be present
    }
    
    await driver.findElement(By.name("login")).click()
    await driver.findElement(By.name("login")).sendKeys("admin123")
    await driver.findElement(By.name("password")).sendKeys("EjudEw_Quoas8@")
    await driver.findElement(By.id("signinbuttonmenu")).click()
  })
})
