<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi;

use MultiFlexi\ActionConfig;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-11-07 at 12:16:27.
 */
class ActionConfigTest extends \PHPUnit\Framework\TestCase
{
    protected ActionConfig $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ActionConfig();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\ActionConfig::saveModeConfigs
     *
     * @todo   Implement testsaveModeConfigs().
     */
    public function testsaveModeConfigs(): void
    {
        $this->assertEquals('', $this->object->saveModeConfigs());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\ActionConfig::saveActionFields
     *
     * @todo   Implement testsaveActionFields().
     */
    public function testsaveActionFields(): void
    {
        $this->assertEquals('', $this->object->saveActionFields());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\ActionConfig::saveActionConfig
     *
     * @todo   Implement testsaveActionConfig().
     */
    public function testsaveActionConfig(): void
    {
        $this->assertEquals('', $this->object->saveActionConfig());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\ActionConfig::getModuleConfig
     *
     * @todo   Implement testgetModuleConfig().
     */
    public function testgetModuleConfig(): void
    {
        $this->assertEquals('', $this->object->getModuleConfig());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\ActionConfig::getRuntemplateConfig
     *
     * @todo   Implement testgetRuntemplateConfig().
     */
    public function testgetRuntemplateConfig(): void
    {
        $this->assertEquals('', $this->object->getRuntemplateConfig());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
