<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi;

use MultiFlexi\Company;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:44.
 */
class CompanyTest extends \PHPUnit\Framework\TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Company();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Company::takeData
     *
     * @todo   Implement testtakeData().
     */
    public function testtakeData(): void
    {
        $this->assertEquals('', $this->object->takeData());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::obtainLogo
     *
     * @todo   Implement testobtainLogo().
     */
    public function testobtainLogo(): void
    {
        $this->assertEquals('', $this->object->obtainLogo());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::getRecordName
     *
     * @todo   Implement testgetRecordName().
     */
    public function testgetRecordName(): void
    {
        $this->assertEquals('', $this->object->getRecordName());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::getLink
     *
     * @todo   Implement testgetLink().
     */
    public function testgetLink(): void
    {
        $this->assertEquals('', $this->object->getLink());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::__destruct
     *
     * @todo   Implement test__destruct().
     */
    public function testDestruct(): void
    {
        $this->assertEquals('', $this->object->__destruct());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::__sleep
     *
     * @todo   Implement test__sleep().
     */
    public function testSleep(): void
    {
        $this->assertEquals('', $this->object->__sleep());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::getEnvironment
     *
     * @todo   Implement testgetEnvironment().
     */
    public function testgetEnvironment(): void
    {
        $this->assertEquals('', $this->object->getEnvironment());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::saveToSQL
     *
     * @todo   Implement testsaveToSQL().
     */
    public function testsaveToSQL(): void
    {
        $this->assertEquals('', $this->object->saveToSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::getMyTable
     *
     * @todo   Implement testgetMyTable().
     */
    public function testgetMyTable(): void
    {
        $this->assertEquals('', $this->object->getMyTable());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::setMyTable
     *
     * @todo   Implement testsetMyTable().
     */
    public function testsetMyTable(): void
    {
        $this->assertEquals('', $this->object->setMyTable());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::setUpDb
     *
     * @todo   Implement testsetUpDb().
     */
    public function testsetUpDb(): void
    {
        $this->assertEquals('', $this->object->setUpDb());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::setUp
     *
     * @todo   Implement testsetUp().
     */
    public function testsetUp(): void
    {
        $this->assertEquals('', $this->object->setUp());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::pdoConnect
     *
     * @todo   Implement testpdoConnect().
     */
    public function testpdoConnect(): void
    {
        $this->assertEquals('', $this->object->pdoConnect());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::getPdo
     *
     * @todo   Implement testgetPdo().
     */
    public function testgetPdo(): void
    {
        $this->assertEquals('', $this->object->getPdo());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::getFluentPDO
     *
     * @todo   Implement testgetFluentPDO().
     */
    public function testgetFluentPDO(): void
    {
        $this->assertEquals('', $this->object->getFluentPDO());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::listingQuery
     *
     * @todo   Implement testlistingQuery().
     */
    public function testlistingQuery(): void
    {
        $this->assertEquals('', $this->object->listingQuery());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::getColumnsFromSQL
     *
     * @todo   Implement testgetColumnsFromSQL().
     */
    public function testgetColumnsFromSQL(): void
    {
        $this->assertEquals('', $this->object->getColumnsFromSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::getDataFromSQL
     *
     * @todo   Implement testgetDataFromSQL().
     */
    public function testgetDataFromSQL(): void
    {
        $this->assertEquals('', $this->object->getDataFromSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::loadFromSQL
     *
     * @todo   Implement testloadFromSQL().
     */
    public function testloadFromSQL(): void
    {
        $this->assertEquals('', $this->object->loadFromSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::dbreload
     *
     * @todo   Implement testdbreload().
     */
    public function testdbreload(): void
    {
        $this->assertEquals('', $this->object->dbreload());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::dbsync
     *
     * @todo   Implement testdbsync().
     */
    public function testdbsync(): void
    {
        $this->assertEquals('', $this->object->dbsync());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::updateToSQL
     *
     * @todo   Implement testupdateToSQL().
     */
    public function testupdateToSQL(): void
    {
        $this->assertEquals('', $this->object->updateToSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::insertToSQL
     *
     * @todo   Implement testinsertToSQL().
     */
    public function testinsertToSQL(): void
    {
        $this->assertEquals('', $this->object->insertToSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::deleteFromSQL
     *
     * @todo   Implement testdeleteFromSQL().
     */
    public function testdeleteFromSQL(): void
    {
        $this->assertEquals('', $this->object->deleteFromSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Company::takeToData
     *
     * @todo   Implement testtakeToData().
     */
    public function testtakeToData(): void
    {
        $this->assertEquals('', $this->object->takeToData());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
