<?php

namespace Test\MultiFlexi;

use MultiFlexi\CompanyEnv;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:38.
 */
class CompanyEnvTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var CompanyEnv
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new CompanyEnv();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers MultiFlexi\CompanyEnv::addEnv
     * @todo   Implement testaddEnv().
     */
    public function testaddEnv()
    {
        $this->assertEquals('', $this->object->addEnv());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\CompanyEnv::updateEnv
     * @todo   Implement testupdateEnv().
     */
    public function testupdateEnv()
    {
        $this->assertEquals('', $this->object->updateEnv());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\CompanyEnv::removeEnv
     * @todo   Implement testremoveEnv().
     */
    public function testremoveEnv()
    {
        $this->assertEquals('', $this->object->removeEnv());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\CompanyEnv::loadEnv
     * @todo   Implement testloadEnv().
     */
    public function testloadEnv()
    {
        $this->assertEquals('', $this->object->loadEnv());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\CompanyEnv::getEnvFields
     * @todo   Implement testgetEnvFields().
     */
    public function testgetEnvFields()
    {
        $this->assertEquals('', $this->object->getEnvFields());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
