<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi;

use MultiFlexi\CompanyJob;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:42.
 */
class CompanyJobTest extends \PHPUnit\Framework\TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new CompanyJob();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\CompanyJob::getColumns
     *
     * @todo   Implement testgetColumns().
     */
    public function testgetColumns(): void
    {
        $this->assertEquals('', $this->object->getColumns());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\CompanyJob::columns
     *
     * @todo   Implement testcolumns().
     */
    public function testcolumns(): void
    {
        $this->assertEquals('', $this->object->columns());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\CompanyJob::addSelectizeValues
     *
     * @todo   Implement testaddSelectizeValues().
     */
    public function testaddSelectizeValues(): void
    {
        $this->assertEquals('', $this->object->addSelectizeValues());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\CompanyJob::completeDataRow
     *
     * @todo   Implement testcompleteDataRow().
     */
    public function testcompleteDataRow(): void
    {
        $this->assertEquals('', $this->object->completeDataRow());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\CompanyJob::tableCode
     *
     * @todo   Implement testtableCode().
     */
    public function testtableCode(): void
    {
        $this->assertEquals('', $this->object->tableCode());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\CompanyJob::setCompany
     *
     * @todo   Implement testsetCompany().
     */
    public function testsetCompany(): void
    {
        $this->assertEquals('', $this->object->setCompany());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\CompanyJob::setApp
     *
     * @todo   Implement testsetApp().
     */
    public function testsetApp(): void
    {
        $this->assertEquals('', $this->object->setApp());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
