<?php

namespace Test\MultiFlexi;

use MultiFlexi\Conffield;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:33.
 */
class ConffieldTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Conffield
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Conffield();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers MultiFlexi\Conffield::takeData
     * @todo   Implement testtakeData().
     */
    public function testtakeData()
    {
        $this->assertEquals('', $this->object->takeData());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Conffield::appConfigs
     * @todo   Implement testappConfigs().
     */
    public function testappConfigs()
    {
        $this->assertEquals('', $this->object->appConfigs());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Conffield::getAppConfigs
     * @todo   Implement testgetAppConfigs().
     */
    public function testgetAppConfigs()
    {
        $this->assertEquals('', $this->object->getAppConfigs());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
