<?php

namespace Test\MultiFlexi;

use MultiFlexi\Customer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:02.
 */
class CustomerTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Customer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Customer();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers MultiFlexi\Customer::getUserName
     * @todo   Implement testgetUserName().
     */
    public function testgetUserName()
    {
        $this->assertEquals('', $this->object->getUserName());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Customer::columns
     * @todo   Implement testcolumns().
     */
    public function testcolumns()
    {
        $this->assertEquals('', $this->object->columns());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Customer::__sleep
     * @todo   Implement test__sleep().
     */
    public function test__sleep()
    {
        $this->assertEquals('', $this->object->__sleep());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
