<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi;

use MultiFlexi\DBEngine;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:44.
 */
class DBEngineTest extends \PHPUnit\Framework\TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new DBEngine();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\DBEngine::loadFromSQL
     *
     * @todo   Implement testloadFromSQL().
     */
    public function testloadFromSQL(): void
    {
        $this->assertEquals('', $this->object->loadFromSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::takemyTable
     *
     * @todo   Implement testtakemyTable().
     */
    public function testtakemyTable(): void
    {
        $this->assertEquals('', $this->object->takemyTable());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::setDetailPage
     *
     * @todo   Implement testsetDetailPage().
     */
    public function testsetDetailPage(): void
    {
        $this->assertEquals('', $this->object->setDetailPage());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getNameColumn
     *
     * @todo   Implement testgetNameColumn().
     */
    public function testgetNameColumn(): void
    {
        $this->assertEquals('', $this->object->getNameColumn());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::translate
     *
     * @todo   Implement testtranslate().
     */
    public function testtranslate(): void
    {
        $this->assertEquals('', $this->object->translate());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getRecordName
     *
     * @todo   Implement testgetRecordName().
     */
    public function testgetRecordName(): void
    {
        $this->assertEquals('', $this->object->getRecordName());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::columns
     *
     * @todo   Implement testcolumns().
     */
    public function testcolumns(): void
    {
        $this->assertEquals('', $this->object->columns());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::editableColumns
     *
     * @todo   Implement testeditableColumns().
     */
    public function testeditableColumns(): void
    {
        $this->assertEquals('', $this->object->editableColumns());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getAll
     *
     * @todo   Implement testgetAll().
     */
    public function testgetAll(): void
    {
        $this->assertEquals('', $this->object->getAll());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getColumnType
     *
     * @todo   Implement testgetColumnType().
     */
    public function testgetColumnType(): void
    {
        $this->assertEquals('', $this->object->getColumnType());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getAllForDataTable
     *
     * @todo   Implement testgetAllForDataTable().
     */
    public function testgetAllForDataTable(): void
    {
        $this->assertEquals('', $this->object->getAllForDataTable());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::addSelectizeValues
     *
     * @todo   Implement testaddSelectizeValues().
     */
    public function testaddSelectizeValues(): void
    {
        $this->assertEquals('', $this->object->addSelectizeValues());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::listingQuery
     *
     * @todo   Implement testlistingQuery().
     */
    public function testlistingQuery(): void
    {
        $this->assertEquals('', $this->object->listingQuery());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getOneRow
     *
     * @todo   Implement testgetOneRow().
     */
    public function testgetOneRow(): void
    {
        $this->assertEquals('', $this->object->getOneRow());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::editorForm
     *
     * @todo   Implement testeditorForm().
     */
    public function testeditorForm(): void
    {
        $this->assertEquals('', $this->object->editorForm());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getSaverFields
     *
     * @todo   Implement testgetSaverFields().
     */
    public function testgetSaverFields(): void
    {
        $this->assertEquals('', $this->object->getSaverFields());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::preprocessPost
     *
     * @todo   Implement testpreprocessPost().
     */
    public function testpreprocessPost(): void
    {
        $this->assertEquals('', $this->object->preprocessPost());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::htmlizeData
     *
     * @todo   Implement testhtmlizeData().
     */
    public function testhtmlizeData(): void
    {
        $this->assertEquals('', $this->object->htmlizeData());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::htmlizeRow
     *
     * @todo   Implement testhtmlizeRow().
     */
    public function testhtmlizeRow(): void
    {
        $this->assertEquals('', $this->object->htmlizeRow());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::foterCallback
     *
     * @todo   Implement testfoterCallback().
     */
    public function testfoterCallback(): void
    {
        $this->assertEquals('', $this->object->foterCallback());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::columnDefs
     *
     * @todo   Implement testcolumnDefs().
     */
    public function testcolumnDefs(): void
    {
        $this->assertEquals('', $this->object->columnDefs());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::saveToSQL
     *
     * @todo   Implement testsaveToSQL().
     */
    public function testsaveToSQL(): void
    {
        $this->assertEquals('', $this->object->saveToSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::prepareToSave
     *
     * @todo   Implement testprepareToSave().
     */
    public function testprepareToSave(): void
    {
        $this->assertEquals('', $this->object->prepareToSave());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::searchString
     *
     * @todo   Implement testsearchString().
     */
    public function testsearchString(): void
    {
        $this->assertEquals('', $this->object->searchString());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getSqlColumns
     *
     * @todo   Implement testgetSqlColumns().
     */
    public function testgetSqlColumns(): void
    {
        $this->assertEquals('', $this->object->getSqlColumns());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getGetDataTableColumns
     *
     * @todo   Implement testgetGetDataTableColumns().
     */
    public function testgetGetDataTableColumns(): void
    {
        $this->assertEquals('', $this->object->getGetDataTableColumns());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::preTableCode
     *
     * @todo   Implement testpreTableCode().
     */
    public function testpreTableCode(): void
    {
        $this->assertEquals('', $this->object->preTableCode());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::tableCode
     *
     * @todo   Implement testtableCode().
     */
    public function testtableCode(): void
    {
        $this->assertEquals('', $this->object->tableCode());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::postTableCode
     *
     * @todo   Implement testpostTableCode().
     */
    public function testpostTableCode(): void
    {
        $this->assertEquals('', $this->object->postTableCode());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::feedSelectize
     *
     * @todo   Implement testfeedSelectize().
     */
    public function testfeedSelectize(): void
    {
        $this->assertEquals('', $this->object->feedSelectize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::feedSelectizeCached
     *
     * @todo   Implement testfeedSelectizeCached().
     */
    public function testfeedSelectizeCached(): void
    {
        $this->assertEquals('', $this->object->feedSelectizeCached());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getFilterOptions
     *
     * @todo   Implement testgetFilterOptions().
     */
    public function testgetFilterOptions(): void
    {
        $this->assertEquals('', $this->object->getFilterOptions());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getHiddenTagets
     *
     * @todo   Implement testgetHiddenTagets().
     */
    public function testgetHiddenTagets(): void
    {
        $this->assertEquals('', $this->object->getHiddenTagets());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::selectize
     *
     * @todo   Implement testselectize().
     */
    public function testselectize(): void
    {
        $this->assertEquals('', $this->object->selectize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getCustomerID
     *
     * @todo   Implement testgetCustomerID().
     */
    public function testgetCustomerID(): void
    {
        $this->assertEquals('', $this->object->getCustomerID());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getResume
     *
     * @todo   Implement testgetResume().
     */
    public function testgetResume(): void
    {
        $this->assertEquals('', $this->object->getResume());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::postCreate
     *
     * @todo   Implement testpostCreate().
     */
    public function testpostCreate(): void
    {
        $this->assertEquals('', $this->object->postCreate());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::validation
     *
     * @todo   Implement testvalidation().
     */
    public function testvalidation(): void
    {
        $this->assertEquals('', $this->object->validation());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::editorOpenJS
     *
     * @todo   Implement testeditorOpenJS().
     */
    public function testeditorOpenJS(): void
    {
        $this->assertEquals('', $this->object->editorOpenJS());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::editorPostCreateJS
     *
     * @todo   Implement testeditorPostCreateJS().
     */
    public function testeditorPostCreateJS(): void
    {
        $this->assertEquals('', $this->object->editorPostCreateJS());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::editorCreateJS
     *
     * @todo   Implement testeditorCreateJS().
     */
    public function testeditorCreateJS(): void
    {
        $this->assertEquals('', $this->object->editorCreateJS());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::editorSubmitCompleteJS
     *
     * @todo   Implement testeditorSubmitCompleteJS().
     */
    public function testeditorSubmitCompleteJS(): void
    {
        $this->assertEquals('', $this->object->editorSubmitCompleteJS());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::renderYesNo
     *
     * @todo   Implement testrenderYesNo().
     */
    public function testrenderYesNo(): void
    {
        $this->assertEquals('', $this->object->renderYesNo());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::renderSelectize
     *
     * @todo   Implement testrenderSelectize().
     */
    public function testrenderSelectize(): void
    {
        $this->assertEquals('', $this->object->renderSelectize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::renderSelectized
     *
     * @todo   Implement testrenderSelectized().
     */
    public function testrenderSelectized(): void
    {
        $this->assertEquals('', $this->object->renderSelectized());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::renderIdLink
     *
     * @todo   Implement testrenderIdLink().
     */
    public function testrenderIdLink(): void
    {
        $this->assertEquals('', $this->object->renderIdLink());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::renderDate
     *
     * @todo   Implement testrenderDate().
     */
    public function testrenderDate(): void
    {
        $this->assertEquals('', $this->object->renderDate());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::renderDocumentLink
     *
     * @todo   Implement testrenderDocumentLink().
     */
    public function testrenderDocumentLink(): void
    {
        $this->assertEquals('', $this->object->renderDocumentLink());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::renderDismisButton
     *
     * @todo   Implement testrenderDismisButton().
     */
    public function testrenderDismisButton(): void
    {
        $this->assertEquals('', $this->object->renderDismisButton());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getColumnsOfType
     *
     * @todo   Implement testgetColumnsOfType().
     */
    public function testgetColumnsOfType(): void
    {
        $this->assertEquals('', $this->object->getColumnsOfType());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::fixIterator
     *
     * @todo   Implement testfixIterator().
     */
    public function testfixIterator(): void
    {
        $this->assertEquals('', $this->object->fixIterator());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getUrlForRecord
     *
     * @todo   Implement testgetUrlForRecord().
     */
    public function testgetUrlForRecord(): void
    {
        $this->assertEquals('', $this->object->getUrlForRecord());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getAttachments
     *
     * @todo   Implement testgetAttachments().
     */
    public function testgetAttachments(): void
    {
        $this->assertEquals('', $this->object->getAttachments());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::presaveCheck
     *
     * @todo   Implement testpresaveCheck().
     */
    public function testpresaveCheck(): void
    {
        $this->assertEquals('', $this->object->presaveCheck());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::finishProcess
     *
     * @todo   Implement testfinishProcess().
     */
    public function testfinishProcess(): void
    {
        $this->assertEquals('', $this->object->finishProcess());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::checkRow
     *
     * @todo   Implement testcheckRow().
     */
    public function testcheckRow(): void
    {
        $this->assertEquals('', $this->object->checkRow());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getRowColor
     *
     * @todo   Implement testgetRowColor().
     */
    public function testgetRowColor(): void
    {
        $this->assertEquals('', $this->object->getRowColor());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::completeDataRow
     *
     * @todo   Implement testcompleteDataRow().
     */
    public function testcompleteDataRow(): void
    {
        $this->assertEquals('', $this->object->completeDataRow());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getColumnInfo
     *
     * @todo   Implement testgetColumnInfo().
     */
    public function testgetColumnInfo(): void
    {
        $this->assertEquals('', $this->object->getColumnInfo());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::getLink
     *
     * @todo   Implement testgetLink().
     */
    public function testgetLink(): void
    {
        $this->assertEquals('', $this->object->getLink());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\DBEngine::__sleep
     *
     * @todo   Implement test__sleep().
     */
    public function testSleep(): void
    {
        $this->assertEquals('', $this->object->__sleep());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
