<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi;

use MultiFlexi\LogToSQL;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:34.
 */
class LogToSQLTest extends \PHPUnit\Framework\TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new LogToSQL();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\LogToSQL::singleton
     *
     * @todo   Implement testsingleton().
     */
    public function testsingleton(): void
    {
        $this->assertEquals('', $this->object->singleton());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\LogToSQL::setCompany
     *
     * @todo   Implement testsetCompany().
     */
    public function testsetCompany(): void
    {
        $this->assertEquals('', $this->object->setCompany());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\LogToSQL::setApplication
     *
     * @todo   Implement testsetApplication().
     */
    public function testsetApplication(): void
    {
        $this->assertEquals('', $this->object->setApplication());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\LogToSQL::setUser
     *
     * @todo   Implement testsetUser().
     */
    public function testsetUser(): void
    {
        $this->assertEquals('', $this->object->setUser());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\LogToSQL::addToLog
     *
     * @todo   Implement testaddToLog().
     */
    public function testaddToLog(): void
    {
        $this->assertEquals('', $this->object->addToLog());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\LogToSQL::venuize
     *
     * @todo   Implement testvenuize().
     */
    public function testvenuize(): void
    {
        $this->assertEquals('', $this->object->venuize());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\LogToSQL::removeEmoji
     *
     * @todo   Implement testremoveEmoji().
     */
    public function testremoveEmoji(): void
    {
        $this->assertEquals('', $this->object->removeEmoji());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
