<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi;

use MultiFlexi\RunTemplate;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:41.
 */
class RunTemplateTest extends \PHPUnit\Framework\TestCase
{
    protected RunTemplate $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new RunTemplate();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\RunTemplate::runTemplateID
     *
     * @todo   Implement testrunTemplateID().
     */
    public function testrunTemplateID(): void
    {
        $this->assertEquals('', $this->object->runTemplateID());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\RunTemplate::setState
     *
     * @todo   Implement testsetState().
     */
    public function testsetState(): void
    {
        $this->assertEquals('', $this->object->setState());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\RunTemplate::performInit
     *
     * @todo   Implement testperformInit().
     */
    public function testperformInit(): void
    {
        $this->assertEquals('', $this->object->performInit());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\RunTemplate::deleteFromSQL
     *
     * @todo   Implement testdeleteFromSQL().
     */
    public function testdeleteFromSQL(): void
    {
        $this->assertEquals('', $this->object->deleteFromSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\RunTemplate::getCompanyEnvironment
     *
     * @todo   Implement testgetCompanyEnvironment().
     */
    public function testgetCompanyEnvironment(): void
    {
        $this->assertEquals('', $this->object->getCompanyEnvironment());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\RunTemplate::getAppEnvironment
     *
     * @todo   Implement testgetAppEnvironment().
     */
    public function testgetAppEnvironment(): void
    {
        $this->assertEquals('', $this->object->getAppEnvironment());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\RunTemplate::getAppInfo
     *
     * @todo   Implement testgetAppInfo().
     */
    public function testgetAppInfo(): void
    {
        $this->assertEquals('', $this->object->getAppInfo());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\RunTemplate::setEnvironment
     *
     * @todo   Implement testsetEnvironment().
     */
    public function testsetEnvironment(): void
    {
        $this->assertEquals('', $this->object->setEnvironment());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\RunTemplate::getAppsForCompany
     *
     * @todo   Implement testgetAppsForCompany().
     */
    public function testgetAppsForCompany(): void
    {
        $this->assertEquals('', $this->object->getPeriodAppsForCompany());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\RunTemplate::setProvision
     *
     * @todo   Implement testsetProvision().
     */
    public function testsetProvision(): void
    {
        $this->assertEquals('', $this->object->setProvision());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
