<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi;

use MultiFlexi\Scheduler;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:33.
 */
class SchedulerTest extends \PHPUnit\Framework\TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Scheduler();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Scheduler::addJob
     *
     * @todo   Implement testaddJob().
     */
    public function testaddJob(): void
    {
        $this->assertEquals('', $this->object->addJob());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Scheduler::getCurrentJobs
     *
     * @todo   Implement testgetCurrentJobs().
     */
    public function testgetCurrentJobs(): void
    {
        $this->assertEquals('', $this->object->getCurrentJobs());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
