<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi;

use MultiFlexi\Servers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:03.
 */
class ServersTest extends \PHPUnit\Framework\TestCase
{
    protected Servers $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Servers();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Servers::takeData
     *
     * @todo   Implement testtakeData().
     */
    public function testtakeData(): void
    {
        $this->assertEquals('', $this->object->takeData());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Servers::prepareRemoteAbraFlexi
     *
     * @todo   Implement testprepareRemoteAbraFlexi().
     */
    public function testprepareRemoteAbraFlexi(): void
    {
        $this->assertEquals('', $this->object->prepareRemoteAbraFlexi());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Servers::setEnvironment
     *
     * @todo   Implement testsetEnvironment().
     */
    public function testsetEnvironment(): void
    {
        $this->assertEquals('', $this->object->setEnvironment());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Servers::getConnectionDetails
     *
     * @todo   Implement testgetConnectionDetails().
     */
    public function testgetConnectionDetails(): void
    {
        $this->assertEquals('', $this->object->getConnectionDetails());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
