<?php

namespace Test\MultiFlexi;

use MultiFlexi\Token;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:08.
 */
class TokenTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Token
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Token();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers MultiFlexi\Token::getUser
     * @todo   Implement testgetUser().
     */
    public function testgetUser()
    {
        $this->assertEquals('', $this->object->getUser());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Token::generate
     * @todo   Implement testgenerate().
     */
    public function testgenerate()
    {
        $this->assertEquals('', $this->object->generate());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
