#!/bin/sh
# postinst script for multiflexi
set -e

. /usr/share/debconf/confmodule

case "$1" in
install | upgrade)

    ;;
configure)

    [ -f "/etc/default/multiflexi" ] && . /etc/default/multiflexi

    if [ -x "/usr/bin/update-multiflexi-env" ]; then
        /usr/bin/update-multiflexi-env
    fi

    ;;

abort-upgrade | abort-remove | abort-deconfigure) ;;

*)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac



#DEBHELPER#

exit 0
