#!/bin/sh
# postinst script for multiflexi-abraflexi
set -e

. /usr/share/debconf/confmodule

# TODO:
#
#    "deb/ease-bootstrap4-widgets-abraflexi": "*",
#
#    {
#      "type": "path",
#      "url": "/usr/share/php/AbraFlexi/"
#    },
#    {
#      "type": "path",
#      "url": "/usr/share/php/AbraFlexiBricks/"
#    },
#    {
#      "type": "path",
#      "url": "/usr/share/php/EaseTWB4WidgetsAbraFlexi/"
#    }
