#!/bin/sh
# postinst script for multiflexi-zabbix
set -e

. /usr/share/debconf/confmodule

composer-debian multiflexi

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then

        if deb-systemd-helper --quiet was-enabled 'zabbix-agent2.service'; then
            deb-systemd-helper reload 'zabbix-agent2.service' >/dev/null || true
        fi
fi
