src/*.php                                 usr/share/multiflexi
src/favicon.ico                           usr/share/multiflexi
src/js/*.js                               usr/share/multiflexi/js
src/assets/Buttons-1.5.6/js/*             usr/share/multiflexi/assets/Buttons-1.5.6/js/
src/assets/Buttons-1.5.6/css/*            usr/share/multiflexi/assets/Buttons-1.5.6/css/
src/assets/Buttons-1.5.6/swf/*            usr/share/multiflexi/assets/Buttons-1.5.6/swf/
src/images/*                              usr/share/multiflexi/images
src/css/*				  usr/share/multiflexi/css
db/migrations/*				  usr/lib/multiflexi/db/migrations
db/seeds/*				  usr/lib/multiflexi/db/seeds
debian/tmp/composer.json                  usr/lib/multiflexi
debian/conf/phinx-adapter.php	          usr/lib/multiflexi
src/MultiFlexi/*.php                      usr/lib/multiflexi/MultiFlexi/
src/MultiFlexi/Env/*.php                  usr/lib/multiflexi/MultiFlexi/Env/
src/MultiFlexi/Command/*.php              usr/lib/multiflexi/MultiFlexi/Command/
src/MultiFlexi/Pohoda/*.php               usr/lib/multiflexi/MultiFlexi/Pohoda/
src/MultiFlexi/AbraFlexi/*.php            usr/lib/multiflexi/MultiFlexi/AbraFlexi/
src/MultiFlexi/Executor/Native.php        usr/lib/multiflexi/MultiFlexi/Executor

src/MultiFlexi/Action/CustomCommand.php   usr/lib/multiflexi/MultiFlexi/Action
#src/MultiFlexi/Action/Github.php          usr/lib/multiflexi/MultiFlexi/Action
src/MultiFlexi/Action/Sleep.php           usr/lib/multiflexi/MultiFlexi/Action
src/MultiFlexi/Action/WebHook.php          usr/lib/multiflexi/MultiFlexi/Action
src/MultiFlexi/Action/LaunchJob.php       usr/lib/multiflexi/MultiFlexi/Action
#src/MultiFlexi/Action/RedmineIssue.php    usr/lib/multiflexi/MultiFlexi/Action
src/MultiFlexi/Action/Reschedule.php      usr/lib/multiflexi/MultiFlexi/Action
src/MultiFlexi/Action/Stop.php            usr/lib/multiflexi/MultiFlexi/Action
#src/MultiFlexi/Action/TriggerJenkins.php  usr/lib/multiflexi/MultiFlexi/Action


src/MultiFlexi/Ui/*.php                   usr/lib/multiflexi/MultiFlexi/Ui/
src/MultiFlexi/Ui/Form/configForm.php     usr/lib/multiflexi/MultiFlexi/Ui/Form/

debian/conf/multiflexi.conf    		  etc/apache2/conf-available
debian/conf/multiflexi.service 		  etc/avahi/services
bin/*					  usr/bin
lib/*					  usr/lib/multiflexi
debian/com.vitexsoftware.multiflexi.metainfo.xml    usr/share/metainfo/
debian/com.vitexsoftware.multiflexi.desktop         usr/share/applications/
multiflexi.svg                 usr/share/icons/hicolor/scalable/apps/
i18n/cs_CZ/LC_MESSAGES/*.mo               usr/share/locale/cs_CZ/LC_MESSAGES/
i18n/en_US/LC_MESSAGES/*.mo               usr/share/locale/en_US/LC_MESSAGES/
tests/multiflexi_probe.multiflexi.app.json usr/share/multiflexi/

src/MultiFlexi/Ui/Form/mServer.php     usr/lib/multiflexi/MultiFlexi/Ui/Form/
src/MultiFlexi/Ui/Form/Office365.php   usr/lib/multiflexi/MultiFlexi/Ui/Form/
src/MultiFlexi/Ui/Form/SQLServer.php   usr/lib/multiflexi/MultiFlexi/Ui/Form/
src/MultiFlexi/Ui/Form/FioBank.php   usr/lib/multiflexi/MultiFlexi/Ui/Form/

