<?php

namespace Test\MultiFlexi\Zabbix;

use MultiFlexi\Zabbix\ZabbixSender;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:06.
 */
class ZabbixSenderTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var ZabbixSender
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ZabbixSender();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers MultiFlexi\Zabbix\ZabbixSender::instance
     * @todo   Implement testinstance().
     */
    public function testinstance()
    {
        $this->assertEquals('', $this->object->instance());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Zabbix\ZabbixSender::configure
     * @todo   Implement testconfigure().
     */
    public function testconfigure()
    {
        $this->assertEquals('', $this->object->configure());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Zabbix\ZabbixSender::disable
     * @todo   Implement testdisable().
     */
    public function testdisable()
    {
        $this->assertEquals('', $this->object->disable());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Zabbix\ZabbixSender::enable
     * @todo   Implement testenable().
     */
    public function testenable()
    {
        $this->assertEquals('', $this->object->enable());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Zabbix\ZabbixSender::send
     * @todo   Implement testsend().
     */
    public function testsend()
    {
        $this->assertEquals('', $this->object->send());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
