<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi\Zabbix;

use MultiFlexi\Zabbix\ZabbixSender;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:06.
 *
 * @no-named-arguments
 */
class ZabbixSenderTest extends \PHPUnit\Framework\TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ZabbixSender();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Zabbix\ZabbixSender::instance
     *
     * @todo   Implement testinstance().
     */
    public function testinstance(): void
    {
        $this->assertEquals('', $this->object->instance());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Zabbix\ZabbixSender::configure
     *
     * @todo   Implement testconfigure().
     */
    public function testconfigure(): void
    {
        $this->assertEquals('', $this->object->configure());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Zabbix\ZabbixSender::disable
     *
     * @todo   Implement testdisable().
     */
    public function testdisable(): void
    {
        $this->assertEquals('', $this->object->disable());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Zabbix\ZabbixSender::enable
     *
     * @todo   Implement testenable().
     */
    public function testenable(): void
    {
        $this->assertEquals('', $this->object->enable());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Zabbix\ZabbixSender::send
     *
     * @todo   Implement testsend().
     */
    public function testsend(): void
    {
        $this->assertEquals('', $this->object->send());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
