<?php

/**
 * MultiFlexi API
 * PHP version 7.4
 *
 * @package AbraFlexi\MultiFlexi
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace MultiFlexi\Model;

use MultiFlexi\BaseModel;

/**
 * Customer
 *
 * @package MultiFlexi\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Customer extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\MultiFlexi\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64",
      "example" : 10
    },
    "enabled" : {
      "type" : "boolean",
      "example" : true
    },
    "settings" : {
      "type" : "string"
    },
    "email" : {
      "type" : "string",
      "format" : "email"
    },
    "firstname" : {
      "type" : "string"
    },
    "lastname" : {
      "type" : "string"
    },
    "password" : {
      "type" : "string"
    },
    "login" : {
      "type" : "string"
    },
    "DatCreate" : {
      "type" : "string",
      "format" : "date-time"
    },
    "DatSave" : {
      "type" : "string",
      "format" : "date-time"
    }
  }
}
SCHEMA;
}
