<?php

/**
 * MultiFlexi API
 * PHP version 7.4
 *
 * @package AbraFlexi\MultiFlexi
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace MultiFlexi\Api;

use PHPUnit\Framework\TestCase;
use MultiFlexi\Api\AbraflexiApi;

/**
 * AbraflexiApiTest Class Doc Comment
 *
 * @package MultiFlexi\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\AbraflexiApi
 */
class AbraflexiApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAbraFlexiById
     *
     * Get AbraFlexi by ID.
     *
     * @covers ::getAbraFlexiById
     */
    public function testGetAbraFlexiById()
    {
        $this->markTestIncomplete(
            'Test of "getAbraFlexiById" method has not been implemented yet.'
        );
    }

    /**
     * Test case for listAbraFlexis
     *
     * Show All AbraFlexis.
     *
     * @covers ::listAbraFlexis
     */
    public function testListAbraFlexis()
    {
        $this->markTestIncomplete(
            'Test of "listAbraFlexis" method has not been implemented yet.'
        );
    }

    /**
     * Test case for setAbraFlexiById
     *
     * Create or Update AbraFlexi record.
     *
     * @covers ::setAbraFlexiById
     */
    public function testSetAbraFlexiById()
    {
        $this->markTestIncomplete(
            'Test of "setAbraFlexiById" method has not been implemented yet.'
        );
    }
}
