<?php

/**
 * MultiFlexi API
 * PHP version 7.4
 *
 * @package AbraFlexi\MultiFlexi
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace MultiFlexi\Api;

use PHPUnit\Framework\TestCase;
use MultiFlexi\Api\AppApi;

/**
 * AppApiTest Class Doc Comment
 *
 * @package MultiFlexi\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\AppApi
 */
class AppApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAppById
     *
     * Get App by ID.
     *
     * @covers ::getAppById
     */
    public function testGetAppById()
    {
        $this->markTestIncomplete(
            'Test of "getAppById" method has not been implemented yet.'
        );
    }

    /**
     * Test case for listApps
     *
     * Show All Apps.
     *
     * @covers ::listApps
     */
    public function testListApps()
    {
        $this->markTestIncomplete(
            'Test of "listApps" method has not been implemented yet.'
        );
    }

    /**
     * Test case for setAppById
     *
     * Create or Update Application.
     *
     * @covers ::setAppById
     */
    public function testSetAppById()
    {
        $this->markTestIncomplete(
            'Test of "setAppById" method has not been implemented yet.'
        );
    }
}
