<?php

/**
 * MultiFlexi API
 * PHP version 7.4
 *
 * @package MultiFlexi
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace MultiFlexi\Api;

use PHPUnit\Framework\TestCase;
use MultiFlexi\Api\CompanyApi;

/**
 * CompanyApiTest Class Doc Comment
 *
 * @package MultiFlexi\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\CompanyApi
 */
class CompanyApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCompanyById
     *
     * Get Company by ID.
     *
     * @covers ::getCompanyById
     */
    public function testGetCompanyById()
    {
        $this->markTestIncomplete(
            'Test of "getCompanyById" method has not been implemented yet.'
        );
    }

    /**
     * Test case for listCompanies
     *
     * Show All Companies.
     *
     * @covers ::listCompanies
     */
    public function testListCompanies()
    {
        $this->markTestIncomplete(
            'Test of "listCompanies" method has not been implemented yet.'
        );
    }

    /**
     * Test case for setCompanyById
     *
     * Create or Update Company.
     *
     * @covers ::setCompanyById
     */
    public function testSetCompanyById()
    {
        $this->markTestIncomplete(
            'Test of "setCompanyById" method has not been implemented yet.'
        );
    }
}
