<?php

/**
 * MultiFlexi API
 * PHP version 7.4
 *
 * @package AbraFlexi\MultiFlexi
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace AbraFlexi\MultiFlexi\Api;

use PHPUnit\Framework\TestCase;
use AbraFlexi\MultiFlexi\Api\DefaultApi;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @package AbraFlexi\MultiFlexi\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \AbraFlexi\MultiFlexi\Api\DefaultApi
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getApiIndex
     *
     * Endpoints listing.
     *
     * @covers ::getApiIndex
     */
    public function testGetApiIndex()
    {
        $this->markTestIncomplete(
            'Test of "getApiIndex" method has not been implemented yet.'
        );
    }

    /**
     * Test case for loginGet
     *
     * Return User's token.
     *
     * @covers ::loginGet
     */
    public function testLoginGet()
    {
        $this->markTestIncomplete(
            'Test of "loginGet" method has not been implemented yet.'
        );
    }

    /**
     * Test case for loginPost
     *
     * Return User's token.
     *
     * @covers ::loginPost
     */
    public function testLoginPost()
    {
        $this->markTestIncomplete(
            'Test of "loginPost" method has not been implemented yet.'
        );
    }

    /**
     * Test case for pingGet
     *
     * Server heartbeat operation.
     *
     * @covers ::pingGet
     */
    public function testPingGet()
    {
        $this->markTestIncomplete(
            'Test of "pingGet" method has not been implemented yet.'
        );
    }
}
