<?php

/**
 * MultiFlexi API
 * PHP version 7.4
 *
 * @package MultiFlexi
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace MultiFlexi\Api;

use PHPUnit\Framework\TestCase;
use MultiFlexi\Api\ServerApi;

/**
 * ServerApiTest Class Doc Comment
 *
 * @package MultiFlexi\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\ServerApi
 */
class ServerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getServerById
     *
     * Get Server by ID.
     *
     * @covers ::getServerById
     */
    public function testGetServerById()
    {
        $this->markTestIncomplete(
            'Test of "getServerById" method has not been implemented yet.'
        );
    }

    /**
     * Test case for listServers
     *
     * Show All Servers.
     *
     * @covers ::listServers
     */
    public function testListServers()
    {
        $this->markTestIncomplete(
            'Test of "listServers" method has not been implemented yet.'
        );
    }

    /**
     * Test case for setServerById
     *
     * Create or Update Server record.
     *
     * @covers ::setServerById
     */
    public function testSetServerById()
    {
        $this->markTestIncomplete(
            'Test of "setServerById" method has not been implemented yet.'
        );
    }
}
