<?php

/**
 * MultiFlexi API
 * PHP version 7.4
 *
 * @package MultiFlexi
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace MultiFlexi\Api;

use PHPUnit\Framework\TestCase;
use MultiFlexi\Api\UserApi;

/**
 * UserApiTest Class Doc Comment
 *
 * @package MultiFlexi\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\UserApi
 */
class UserApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getUserById
     *
     * Get User by ID.
     *
     * @covers ::getUserById
     */
    public function testGetUserById()
    {
        $this->markTestIncomplete(
            'Test of "getUserById" method has not been implemented yet.'
        );
    }

    /**
     * Test case for listUsers
     *
     * Show All Users.
     *
     * @covers ::listUsers
     */
    public function testListUsers()
    {
        $this->markTestIncomplete(
            'Test of "listUsers" method has not been implemented yet.'
        );
    }

    /**
     * Test case for setUserById
     *
     * Create or Update User.
     *
     * @covers ::setUserById
     */
    public function testSetUserById()
    {
        $this->markTestIncomplete(
            'Test of "setUserById" method has not been implemented yet.'
        );
    }
}
