<?php

/**
 * MultiFlexi API
 * PHP version 7.4
 *
 * @package AbraFlexi\MultiFlexi
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace AbraFlexi\MultiFlexi\Model;

use PHPUnit\Framework\TestCase;
use AbraFlexi\MultiFlexi\Model\AppCompany;

/**
 * AppCompanyTest Class Doc Comment
 *
 * @package AbraFlexi\MultiFlexi\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \AbraFlexi\MultiFlexi\Model\AppCompany
 */
class AppCompanyTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AppCompany"
     */
    public function testAppCompany()
    {
        $testAppCompany = new AppCompany();
        $namespacedClassname = AppCompany::getModelsNamespace() . '\\AppCompany';
        $this->assertSame('\\' . AppCompany::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "AppCompany" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $this->markTestIncomplete(
            'Test of "id" property in "AppCompany" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "appId"
     */
    public function testPropertyAppId()
    {
        $this->markTestIncomplete(
            'Test of "appId" property in "AppCompany" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "iterv"
     */
    public function testPropertyIterv()
    {
        $this->markTestIncomplete(
            'Test of "iterv" property in "AppCompany" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = AppCompany::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
