<?php

/**
 * MultiFlexi API
 * PHP version 7.4
 *
 * @package AbraFlexi\MultiFlexi
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace MultiFlexi\Model;

use PHPUnit\Framework\TestCase;
use AbraFlexi\MultiFlexi\Model\App;

/**
 * AppTest Class Doc Comment
 *
 * @package AbraFlexi\MultiFlexi\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \AbraFlexi\MultiFlexi\Model\App
 */
class AppTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "App"
     */
    public function testApp()
    {
        $testApp = new App();
        $namespacedClassname = App::getModelsNamespace() . '\\App';
        $this->assertSame('\\' . App::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "App" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $this->markTestIncomplete(
            'Test of "id" property in "App" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        $this->markTestIncomplete(
            'Test of "name" property in "App" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "executable"
     */
    public function testPropertyExecutable()
    {
        $this->markTestIncomplete(
            'Test of "executable" property in "App" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
        $this->markTestIncomplete(
            'Test of "tags" property in "App" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        $this->markTestIncomplete(
            'Test of "status" property in "App" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = App::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
