<?php

/**
 * MultiFlexi API
 * PHP version 7.4
 *
 * @package AbraFlexi\MultiFlexi
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace AbraFlexi\MultiFlexi\Model;

use PHPUnit\Framework\TestCase;
use AbraFlexi\MultiFlexi\Model\ConfField;

/**
 * ConfFieldTest Class Doc Comment
 *
 * @package AbraFlexi\MultiFlexi\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \AbraFlexi\MultiFlexi\Model\ConfField
 */
class ConfFieldTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ConfField"
     */
    public function testConfField()
    {
        $testConfField = new ConfField();
        $namespacedClassname = ConfField::getModelsNamespace() . '\\ConfField';
        $this->assertSame('\\' . ConfField::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "ConfField" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $this->markTestIncomplete(
            'Test of "id" property in "ConfField" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "appId"
     */
    public function testPropertyAppId()
    {
        $this->markTestIncomplete(
            'Test of "appId" property in "ConfField" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "keyname"
     */
    public function testPropertyKeyname()
    {
        $this->markTestIncomplete(
            'Test of "keyname" property in "ConfField" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        $this->markTestIncomplete(
            'Test of "type" property in "ConfField" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        $this->markTestIncomplete(
            'Test of "description" property in "ConfField" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "defval"
     */
    public function testPropertyDefval()
    {
        $this->markTestIncomplete(
            'Test of "defval" property in "ConfField" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = ConfField::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
