<?php

/**
 * MultiFlexi API
 * PHP version 7.4
 *
 * @package MultiFlexi
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace MultiFlexi\Model;

use PHPUnit\Framework\TestCase;
use MultiFlexi\Model\Server;

/**
 * ServerTest Class Doc Comment
 *
 * @package MultiFlexi\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Model\Server
 */
class ServerTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Server"
     */
    public function testServer()
    {
        $testServer = new Server();
        $namespacedClassname = Server::getModelsNamespace() . '\\Server';
        $this->assertSame('\\' . Server::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "Server" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $this->markTestIncomplete(
            'Test of "id" property in "Server" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        $this->markTestIncomplete(
            'Test of "name" property in "Server" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
        $this->markTestIncomplete(
            'Test of "url" property in "Server" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
        $this->markTestIncomplete(
            'Test of "user" property in "Server" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
        $this->markTestIncomplete(
            'Test of "password" property in "Server" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "datCreate"
     */
    public function testPropertyDatCreate()
    {
        $this->markTestIncomplete(
            'Test of "datCreate" property in "Server" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "datSave"
     */
    public function testPropertyDatSave()
    {
        $this->markTestIncomplete(
            'Test of "datSave" property in "Server" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = Server::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
