<?php

namespace Test\MultiFlexi\Env;

use MultiFlexi\Env\Company;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:40.
 */
class CompanyTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Company
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Company();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers MultiFlexi\Env\Company::allKeysHandled
     * @todo   Implement testallKeysHandled().
     */
    public function testallKeysHandled()
    {
        $this->assertEquals('', $this->object->allKeysHandled());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Env\Company::getEnvironment
     * @todo   Implement testgetEnvironment().
     */
    public function testgetEnvironment()
    {
        $this->assertEquals('', $this->object->getEnvironment());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
