<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi\Env;

use MultiFlexi\Env\Pohoda;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-07 at 13:03:39.
 */
class PohodaTest extends \PHPUnit\Framework\TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Pohoda();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \MultiFlexi\Env\Pohoda::allKeysHandled
     *
     * @todo   Implement testallKeysHandled().
     */
    public function testallKeysHandled(): void
    {
        $this->assertEquals('', $this->object->allKeysHandled());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \MultiFlexi\Env\Pohoda::getEnvironment
     *
     * @todo   Implement testgetEnvironment().
     */
    public function testgetEnvironment(): void
    {
        $this->assertEquals('', $this->object->getEnvironment());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
